---
title: "Evictions"
---

This section of the book contains papers related to evictions. Below are a list of the chapters and their abstracts.

@sec-Hepburn-Louis-Desmond-2020

**Title**: Racial and Gender Disparities among Evicted Americans

**Abstract**: Drawing on millions of court records of eviction cases filed between 2012 and 2016 in 39 states, this study documents the racial and gender demographics of America’s evicted population. Black renters received a disproportionate share of eviction filings and experienced the highest rates of eviction filing and eviction judgment. Black and Latinx female renters faced higher eviction rates than their male counterparts. Black and Latinx renters were also more likely to be serially filed against for eviction at the same address. These findings represent the most comprehensive investigation to date of racial and gender disparities among evicted renters in the United States.

@sec-Collinson-et-al-2025-children

**Title**: The Effects Of Eviction On Children

**Abstract**: Eviction may be an important channel for the intergenerational transmission of poverty, and concerns about its effects on children are often raised as a rationale for tenant protection policies. We study how eviction impacts children's home environment, school engagement, educational achievement, and high school completion by assembling new data sets linking eviction court records in Chicago and New York to administrative public school records and restricted Census records. To disentangle the consequences of eviction from the effects of correlated sources of economic distress, we use a research design based on the random assignment of court cases to judges who vary in their leniency. We find that eviction increases children's residential mobility, homelessness, and likelihood of doubling up with grandparents or other adults. Eviction also disrupts school engagement, causing increased absences and school changes. While we find little impact on elementary and middle school test scores, eviction substantially reduces high school course credits. Lastly, we find that eviction reduces high school graduation and use a novel bounding method to show that this finding is not driven by differential attrition. The disruptive effects of eviction appear worse for older children and boys. Our evidence suggests that the 
impact of eviction on children runs through the disruption to the home environment or school engagement rather than deterioration in school or neighborhood quality, and may be moderated by access to family support networks.


@sec-Collinson-et-al-2024-era

**Title**: The Effects Of Emergency Rental Assistance During The Pandemic: Evidence From Four Cities

**Abstract**: Short-term rental assistance programs expanded to unprecedented scale during the COVID-19 pandemic. We evaluate these programs using applications to five assistance programs that disbursed more than$200 million via lottery. Drawing on administrative and original survey data, we estimate effects on rent payment, housing stability, financial distress, and health. Assistance led to increases in rent payment and reduced tenants’ concerns about eviction. We also find suggestive evidence of improvements in self-reported mental and physical health. However, we find little effect on housing stability or financial distress. Relative to Economic Impact Payments, we find that ERA was well-targeted to high-poverty neighborhoods.


@sec-Collinson-et-al-2024-legal

**Title**: Equilibrium Effects of Eviction Protections: The Case of Legal Assistance

**Abstract**: “Right-to-counsel” programs provide free legal assistance to tenants in eviction court. Legal assistance can delay or prevent eviction. However, large-scale legal assistance programs can also generate costs for tenants due to equilibrium rental market responses. In this paper, we study how right to counsel impacts rental markets when implemented at scale, and quantify the policy’s impact on tenant welfare. Leveraging the geographic rollout of New York City’s program, we find listed rent prices rose by \$22-\$38/month within two years of policy implementation, with larger increases in areas with higher baseline eviction rates. We do not find evidence that landlords adjusted on other margins, such as tenant screening or improvements to habitability. Guided by these results, we develop a framework to evaluate the policy’s welfare implications for tenants, incorporating the trade-off between protection from eviction and higher rent prices. We quantify the parameters of our framework using linked data on eviction court cases, rental housing listings, and tenant earnings trajectories. Despite the direct benefits and insurance value of stronger eviction protections, the estimated price increases are large enough to generate a small net reduction in ex-ante tenant welfare.

@sec-Estes-Nelson-2025

**Title**: Justice Divided, Justice Denied? The Effects of Court Rules on Eviction Outcomes in Los Angeles County

**Abstract**: More than 40,000 households in Los Angeles County face eviction each year. Pursuing policies that reduce the number of evictions is of growing importance to state and local policymakers, but the causes and consequences of eviction are poorly understood. By collecting eviction docket records and linking them to administrative data, we are able to study an important institutional determinant of eviction in LA County: how courts assign cases. Because eviction cases are assigned to courthouses based on a unique spatial assignment rule, we test the effect of court assignment on default eviction probability using a regression discontinuity design. We show that courthouse assignment can increase the probability of default eviction by 0.7–23.1 percentage points.